version: 2

project_name: pine

builds:
  - id: pine
    main: .
    binary: pine
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'main.buildVersion={{ .Version }}' -X 'main.buildCommit={{ .ShortCommit }}' -X 'main.buildGoVersion={{ .Env.GOVERSION }}'

archives:
  - id: release
    ids:
      - pine
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: SHA256SUMS.txt
  algorithm: sha256

release:
  prerelease: auto
